from dotenv import load_dotenv
import os

load_dotenv()

LLM_MODELS_SETTINGS = {
    "deepseek-v3-official": {
        "api_key": os.getenv("DEEPSEEK_API_KEY"),
        "base_url": "https://api.deepseek.com",
        "model_name": "deepseek-chat",
        "comment": "DeepSeek V3 Official",
        "reasoning": False,
    },
    "deepseek-v3.2-think": {
        "api_key": os.getenv("DEEPSEEK_API_KEY"),
        "base_url": "https://api.deepseek.com",
        "model_name": "deepseek-reasoner",
        "comment": "DeepSeek V3.2 think",
        "reasoning": True,
    },
    "deepseek-v3-ali": {
        "api_key": os.getenv("DASHSCOPE_API_KEY"),
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-v3",
        "comment": "DeepSeek V3 Ali",
        "reasoning": False,
    },
    "deepseek-r1-ali": {
        "api_key": os.getenv("DASHSCOPE_API_KEY"),
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model_name": "deepseek-r1",
        "comment": "DeepSeek R1 Reasoning Model Ali",
        "reasoning": True,
    },
    "deepseek-v3-ark": {
        "api_key": os.getenv("ARK_API_KEY"),
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "model_name": "deepseek-v3-250324",
        "comment": "DeepSeek V3 Ark",
        "reasoning": False,
    },
    "deepseek-r1-ark": {
        "api_key": os.getenv("ARK_API_KEY"),
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "model_name": "deepseek-r1-250120",
        "comment": "DeepSeek R1 Reasoning Model Ark",
        "reasoning": True,
    },
    "qwen-max-latest": {
        "api_key": os.getenv("DASHSCOPE_API_KEY"),
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-max-latest",
        "comment": "Qwen Max",
        "reasoning": False,
    },
    "qwen-vl-max": {
        "api_key": os.getenv("DASHSCOPE_API_KEY"),
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen-vl-max",
        "comment": "qwen-vl-max",
        "reasoning": False,
    },
    "qwen2.5-vl-72b-instruct": {
        "api_key": os.getenv("DASHSCOPE_API_KEY"),
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-vl-72b-instruct",
        "comment": "qwen2.5-vl-72b-instruct",
        "reasoning": False,
    },
    "qwen2.5-vl-32b-instruct": {
        "api_key": os.getenv("DASHSCOPE_API_KEY"),
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-vl-32b-instruct",
        "comment": "qwen2.5-vl-32b-instruct",
        "reasoning": False,
    },
    "qwen2.5-72b-instruct": {
        "api_key": os.getenv("DASHSCOPE_API_KEY"),
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen2.5-72b-instruct",
        "comment": "qwen2.5-72b-instruct",
        "reasoning": False,
    },
    "qwen3-235b-a22b": {
        "api_key": os.getenv("DASHSCOPE_API_KEY"),
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-235b-a22b",
        "comment": "qwen3-235b-a22b",
        "reasoning": True,
    },
    "gemini-2.5-flash": {
        "api_key": os.getenv("LAOZHANG_API_KEY"),
        "base_url": "https://api.laozhang.ai/v1",
        "model_name": "gemini-2.5-flash",
        "comment": "gemini-2.5-flash",
        "reasoning": True,
    },
    "gpt-5": {
        "api_key": os.getenv("LAOZHANG_API_KEY"),
        "base_url": "https://api.laozhang.ai/v1",
        "model_name": "gpt-5",
        "comment": "gpt-5",
        "reasoning": True,
    },
    "gemini-2.5-pro": {
        "api_key": os.getenv("LAOZHANG_API_KEY"),
        "base_url": "https://api.laozhang.ai/v1",
        "model_name": "gemini-2.5-pro",
        "comment": "gemini-2.5-pro",
        "reasoning": True,
    },
    "qwen3-vl-plus": {
        "api_key": os.getenv("QWEN_API_KEY"),
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-vl-plus",
        "comment": "qwen3-vl-plus",
        "reasoning": True,
    },
    "qwen3-vl-235B": {
        "api_key": os.getenv("QWEN_API_KEY"),
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model_name": "qwen3-vl-235b-a22b-instruct",
        "comment": "qwen3-vl-235B",
        "reasoning": True,
    },
}